# Generated by Django 5.2.17 on 2026-10-05 19:44

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models
from wagtail.images import get_image_model_string


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtail_feathers', '0011_alter_countrygroup_countries'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(get_image_model_string()),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('heading', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('action_text', models.CharField(blank=True, help_text='Form action text.', max_length=32)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
                ('template_variant', models.CharField(blank=True, help_text="Optional template variant (e.g., 'contact', 'newsletter'). Leave empty for default template.", max_length=50, verbose_name='Template Variant')),
            ],
            options={
                'verbose_name': 'Form Base Page',
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('featherbasepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtail_feathers.featherbasepage')),
                ('header', wagtail.fields.StreamField([('heading', 8), ('image', 13), ('hero', 35), ('cta', 43)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Additional CSS classes (space-separated)', 'label': 'CSS Classes', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Custom HTML ID for this block', 'label': 'HTML ID', 'max_length': 50, 'required': False}), 2: ('wagtail_feathers.blocks.ThemeVariantChooserBlock', (), {'component_type': 'heading', 'default': 'default', 'help_text': 'Select a theme variant for this component', 'label': 'Theme variant', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('classname', 0), ('style_id', 1), ('theme_variant', 2)]], {}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Full width', 'required': False}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Sub Heading', 'max_length': 120, 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'help_text': 'Text alignment for the hero content'}), 8: ('wagtail.blocks.StructBlock', [[('theme', 3), ('fluid', 4), ('heading', 5), ('sub_heading', 6), ('alignment', 7)]], {'label': 'Heading', 'required': False}), 9: ('wagtail_feathers.blocks.ThemeVariantChooserBlock', (), {'component_type': 'image', 'default': 'default', 'help_text': 'Select a theme variant for this component', 'label': 'Theme variant', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('classname', 0), ('style_id', 1), ('theme_variant', 9)]], {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': "If left blank, the image's global alt text will be used.", 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('theme', 10), ('fluid', 4), ('image', 11), ('image_alt_text', 12)]], {'label': 'Image', 'required': False}), 14: ('wagtail_feathers.blocks.ThemeVariantChooserBlock', (), {'component_type': 'hero', 'default': 'default', 'help_text': 'Select a theme variant for this component', 'label': 'Theme variant', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('classname', 0), ('style_id', 1), ('theme_variant', 14)]], {}), 16: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Main headline for the hero section (max 120 characters)', 'max_length': 120}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional subheadline or tagline (max 200 characters)', 'max_length': 200, 'required': False}), 18: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Optional description text with basic formatting', 'required': False}), 19: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for the hero section', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text for background image (for accessibility)', 'max_length': 100, 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'max_length': 50}), 22: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 23: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use link's title.", 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('page', 22), ('document', 23), ('title', 24)]], {}), 26: ('wagtail.blocks.URLBlock', (), {}), 27: ('wagtail.blocks.CharBlock', (), {'required': False}), 28: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Open the link in a new tab', 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('link', 26), ('title', 27), ('link_target', 28)]], {}), 30: ('wagtail.blocks.StreamBlock', [[('internal', 25), ('external', 29)]], {'max_num': 1}), 31: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], 'help_text': 'Button style'}), 32: ('wagtail.blocks.StructBlock', [[('text', 21), ('link', 30), ('style', 31)]], {'label': 'Call-to-Action Button'}), 33: ('wagtail.blocks.StreamBlock', [[('cta', 32)]], {'help_text': 'Add up to 3 call-to-action buttons', 'label': 'Call-to-Action Buttons', 'max_num': 3, 'required': False}), 34: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0', 'No overlay'), ('25', 'Light overlay (25%)'), ('50', 'Medium overlay (50%)'), ('75', 'Dark overlay (75%)'), ('85', 'Darker overlay (85%)')], 'help_text': 'Overlay opacity for better text readability over background image', 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('theme', 15), ('heading', 16), ('sub_heading', 17), ('description', 18), ('background_image', 19), ('background_image_alt', 20), ('call_to_actions', 33), ('fluid', 4), ('alignment', 7), ('overlay_opacity', 34)]], {'label': 'Hero Section', 'required': False}), 36: ('wagtail_feathers.blocks.ThemeVariantChooserBlock', (), {'component_type': 'cta', 'default': 'default', 'help_text': 'Select a theme variant for this component', 'label': 'Theme variant', 'required': False}), 37: ('wagtail.blocks.StructBlock', [[('classname', 0), ('style_id', 1), ('theme_variant', 36)]], {}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': 'Call-to-action heading', 'max_length': 100}), 39: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Supporting text for the call-to-action', 'required': False}), 40: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text for the action button', 'max_length': 50}), 41: ('wagtail.blocks.StreamBlock', [[('internal', 25), ('external', 29)]], {'help_text': 'Link for the action button', 'max_num': 1}), 42: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('accent', 'Accent')], 'help_text': 'Background color theme for the CTA section'}), 43: ('wagtail.blocks.StructBlock', [[('theme', 37), ('heading', 38), ('text', 39), ('button_text', 40), ('button_link', 41), ('background_color', 42)]], {'label': 'Call to Action', 'required': False})}, help_text='Page header blocks.')),
            ],
            options={
                'verbose_name': 'Web Base Page',
                'abstract': False,
            },
            bases=('wagtail_feathers.featherbasepage',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('featherbasepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtail_feathers.featherbasepage')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('publication_date', models.DateField(default=django.utils.timezone.now, help_text='Official first publication date.')),
                ('revision_date', models.DateField(blank=True, help_text='Official last revision date.', null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtail_feathers.featherbasepage',),
        ),
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='testapp.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
