# Generated by Django 5.2.4 on 2026-01-29 18:59

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_feathers', '0003_alter_featherbasepage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmenu',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Auto-generated from name, but can be edited', populate_from='name'),
        ),
        migrations.AlterField(
            model_name='footernavigation',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Auto-generated from name, but can be edited', populate_from='name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Auto-generated from name, but can be edited', populate_from='name'),
        ),
        migrations.AlterField(
            model_name='nestedmenu',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Auto-generated from name, but can be edited', populate_from='name'),
        ),
        migrations.AddConstraint(
            model_name='flatmenu',
            constraint=models.UniqueConstraint(fields=('slug', 'locale'), name='unique_flatmenu_slug_locale'),
        ),
        migrations.AddConstraint(
            model_name='footernavigation',
            constraint=models.UniqueConstraint(fields=('slug', 'locale'), name='unique_footernavigation_slug_locale'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('slug', 'locale'), name='unique_menu_slug_locale'),
        ),
        migrations.AddConstraint(
            model_name='nestedmenu',
            constraint=models.UniqueConstraint(fields=('slug', 'locale'), name='unique_nestedmenu_slug_locale'),
        ),
    ]
