# Generated by Django 6.0.5 on 2026-05-28 02:03

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_feathers', '0007_alter_featherbasepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrygroup',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, help_text='Select countries that belong to this group', max_length=749, multiple=True),
        ),
    ]
