# Generated by Django 5.2.4 on 2025-08-09 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_feathers', '0009_category_add_translatable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageauthor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_feathers.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='pageauthor',
            name='type',
            field=models.ForeignKey(blank=True, help_text="Select the author's role or type", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_feathers.authortype', verbose_name='Type'),
        ),
    ]
