# Generated by Django 5.2.5 on 2025-08-18 22:57

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_feathers', '0010_alter_pageauthor_person_alter_pageauthor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this country group (e.g., 'ACP Countries', 'EU Countries', 'West Africa')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this country group')),
                ('countries', django_countries.fields.CountryField(blank=True, help_text='Select countries that belong to this group', max_length=746, multiple=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Group',
                'verbose_name_plural': 'Country Groups',
                'ordering': ['name'],
            },
        ),
    ]
