# Generated by Django 5.2.17 on 2026-10-05 19:41

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_feathers', '0010_alter_countrygroup_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrygroup',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, help_text='Select countries that belong to this group', max_length=1000, multiple=True),
        ),
    ]
