# Generated by Django 5.2.5 on 2025-08-22 22:12

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_feathers', '0011_countrygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
