# Generated by Django 5.2.5 on 2025-08-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_feathers', '0013_rename_faq_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
