# Generated by Django 5.2.5 on 2025-08-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_feathers', '0014_alter_faq_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.CharField(help_text='The FAQ question', max_length=255),
        ),
    ]
